import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'

import { BriefScreen, publishedLabel } from '../src/components/brief-screen'
import { type DailyBrief } from '../src/domain/brief'
import { dailyBriefFixture } from './fixtures/market'

function render(latest: DailyBrief | undefined): string {
  return renderToStaticMarkup(createElement(BriefScreen, { latest, onSymbol: () => undefined }))
}

describe('the brief screen', () => {
  it('shows the trade line, the rendered thesis, and the reading list', () => {
    const html = render(dailyBriefFixture)
    expect(html).toContain('Buy NVDA 205c 10/16/26')
    expect(html).not.toContain('bullish')
    expect(html).not.toContain('>Trades<')
    expect(html).toContain('<strong>Catalyst:</strong> demand checks keep the AI capex case alive.')
    expect(html).toContain('<li>IV rank 22, options are cheap.</li>')
    expect(html).toContain('href="https://www.reuters.com/markets/us/capex-2026"')
    expect(html).toContain('<span title="Generated by">@cf/zai-org/glm-5.3</span>')
    expect(html).toContain('Previous')
  })

  it('renders model markup as text, never as HTML', () => {
    const html = render({
      ...dailyBriefFixture,
      recommendations: [{ ...dailyBriefFixture.recommendations[0]!, thesis: '<img src=x onerror=alert(1)> and [x](javascript:alert(1))' }],
    })
    expect(html).toContain('&lt;img src=x onerror=alert(1)&gt;')
    expect(html).not.toContain('href="javascript:')
    expect(html).toContain('[x](javascript:alert(1))')
  })

  it('puts the trades before the headlines, and shows a headline as its title, snippet and host', () => {
    const html = render({
      ...dailyBriefFixture,
      links: [
        { url: 'https://www.reuters.com/markets/us/capex-2026', title: 'Capex <b>holds</b>', snippet: 'Hyperscalers keep spending.' },
        { url: 'https://www.bloomberg.com/news/x' },
      ],
    })
    expect(html.indexOf('aria-label="Trades"')).toBeLessThan(html.indexOf('Headlines'))
    expect(html).not.toContain('Reading')
    expect(html).toContain('Capex &lt;b&gt;holds&lt;/b&gt;')
    expect(html).toContain('Hyperscalers keep spending.')
    expect(html).toContain('>www.reuters.com<')
    // A titled headline does not repeat its URL as text; an untitled one is titled by its host,
    // with its path, never a title derived from the slug.
    expect(html).not.toContain('>https://www.reuters.com/markets/us/capex-2026')
    expect(html).toContain('<span class="brief-headline-title">www.bloomberg.com<')
    expect(html).toContain('>/news/x<')
    expect(html).toContain('href="https://www.bloomberg.com/news/x"')
    expect(html).toContain('rel="noreferrer" target="_blank"')
  })

  it('says so when nothing has been published', () => {
    const html = render(undefined)
    expect(html).toContain('No brief yet')
    expect(html).not.toContain('Previous')
  })
})

describe('brief publication line', () => {
  it('shows only the time when the brief was published on its own market day in New York', () => {
    // 16:37 UTC on Sep 25 is 12:37 PM EDT the same day.
    expect(publishedLabel({ marketDate: '2026-09-25', publishedAt: '2026-09-25T16:37:30.152Z' })).toBe('12:37 PM EDT')
  })

  it('keeps the date when the New York day differs from the market day', () => {
    // 02:00 UTC on Sep 26 is still Sep 25 in New York, so that is the same day...
    expect(publishedLabel({ marketDate: '2026-09-25', publishedAt: '2026-09-26T02:00:00.000Z' })).toBe('10:00 PM EDT')
    // ...while a republication days later names its own date.
    expect(publishedLabel({ marketDate: '2026-09-25', publishedAt: '2026-09-28T14:00:00.000Z' })).toBe('Sep 28, 2026, 10:00 AM EDT')
  })

  it('makes the trade line the way into Watch, without a second symbol button', () => {
    const html = render(dailyBriefFixture)
    const trade = dailyBriefFixture.recommendations[0]!
    expect(html).toContain(`title="Open ${trade.symbol} in Watch"`)
    expect(html).toContain(`>${trade.trade}</button>`)
    expect(html).not.toContain(`>${trade.symbol}</button>`)
  })
  it('says "Not financial advice." once, in the footer after the headlines', () => {
    const html = render(dailyBriefFixture)
    expect(html.split('Not financial advice.')).toHaveLength(2)
    expect(html.indexOf('brief-headlines-title')).toBeLessThan(html.indexOf('Not financial advice.'))
    expect(html).toContain('href="/disclosures"')
  })
})
