/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppWatchRouteImport } from './routes/_app.watch'
import { Route as ApiAgentLoginsRouteImport } from './routes/api.agent-logins'
import { Route as ApiFavoritesRouteImport } from './routes/api.favorites'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiMcpTokensRouteImport } from './routes/api.mcp-tokens'
import { Route as ApiPublicCatalystRefreshRouteImport } from './routes/api.public-catalyst-refresh'
import { Route as ApiPublicCatalystsRouteImport } from './routes/api.public-catalysts'
import { Route as ApiPublicDailyBriefsRouteImport } from './routes/api.public-daily-briefs'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api.public-snapshot'
import { Route as ApiPublicSymbolEvidenceRouteImport } from './routes/api.public-symbol-evidence'
import { Route as ApiPublicSymbolSearchRouteImport } from './routes/api.public-symbol-search'
import { Route as ApiPublicYearCandlesRouteImport } from './routes/api.public-year-candles'
import { Route as ApiSnapshotRouteImport } from './routes/api.snapshot'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as ApiViewerRouteImport } from './routes/api.viewer'
import { Route as AuthorizeIndexRouteImport } from './routes/authorize.index'
import { Route as AuthorizeConsentRouteImport } from './routes/authorize.consent'
import { Route as ConnectAgentRouteImport } from './routes/connect.agent'
import { Route as ApiAgentLoginsExchangeRouteImport } from './routes/api.agent-logins.exchange'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiBrokersTastytradeAuthorizeRouteImport } from './routes/api.brokers.tastytrade.authorize'
import { Route as ApiBrokersTastytradeCallbackRouteImport } from './routes/api.brokers.tastytrade.callback'
import { Route as ApiBrokersTastytradeExchangeRouteImport } from './routes/api.brokers.tastytrade.exchange'
import { Route as ApiBrokersTastytradeTokenRouteImport } from './routes/api.brokers.tastytrade.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgentLoginsRoute = ApiAgentLoginsRouteImport.update({
  id: '/api/agent-logins',
  path: '/api/agent-logins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesRoute = ApiFavoritesRouteImport.update({
  id: '/api/favorites',
  path: '/api/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTokensRoute = ApiMcpTokensRouteImport.update({
  id: '/api/mcp-tokens',
  path: '/api/mcp-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalystRefreshRoute =
  ApiPublicCatalystRefreshRouteImport.update({
    id: '/api/public-catalyst-refresh',
    path: '/api/public-catalyst-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalystsRoute = ApiPublicCatalystsRouteImport.update({
  id: '/api/public-catalysts',
  path: '/api/public-catalysts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyBriefsRoute = ApiPublicDailyBriefsRouteImport.update({
  id: '/api/public-daily-briefs',
  path: '/api/public-daily-briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public-snapshot',
  path: '/api/public-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolEvidenceRoute = ApiPublicSymbolEvidenceRouteImport.update({
  id: '/api/public-symbol-evidence',
  path: '/api/public-symbol-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolSearchRoute = ApiPublicSymbolSearchRouteImport.update({
  id: '/api/public-symbol-search',
  path: '/api/public-symbol-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYearCandlesRoute = ApiPublicYearCandlesRouteImport.update({
  id: '/api/public-year-candles',
  path: '/api/public-year-candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewerRoute = ApiViewerRouteImport.update({
  id: '/api/viewer',
  path: '/api/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeIndexRoute = AuthorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeConsentRoute = AuthorizeConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthorizeRoute,
} as any)
const ConnectAgentRoute = ConnectAgentRouteImport.update({
  id: '/connect/agent',
  path: '/connect/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentLoginsExchangeRoute = ApiAgentLoginsExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => ApiAgentLoginsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokersTastytradeAuthorizeRoute =
  ApiBrokersTastytradeAuthorizeRouteImport.update({
    id: '/api/brokers/tastytrade/authorize',
    path: '/api/brokers/tastytrade/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBrokersTastytradeCallbackRoute =
  ApiBrokersTastytradeCallbackRouteImport.update({
    id: '/api/brokers/tastytrade/callback',
    path: '/api/brokers/tastytrade/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBrokersTastytradeExchangeRoute =
  ApiBrokersTastytradeExchangeRouteImport.update({
    id: '/api/brokers/tastytrade/exchange',
    path: '/api/brokers/tastytrade/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBrokersTastytradeTokenRoute =
  ApiBrokersTastytradeTokenRouteImport.update({
    id: '/api/brokers/tastytrade/token',
    path: '/api/brokers/tastytrade/token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRouteWithChildren
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AppConnectRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/watch': typeof AppWatchRoute
  '/api/agent-logins': typeof ApiAgentLoginsRouteWithChildren
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-catalysts': typeof ApiPublicCatalystsRoute
  '/api/public-daily-briefs': typeof ApiPublicDailyBriefsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/connect/agent': typeof ConnectAgentRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/api/agent-logins/exchange': typeof ApiAgentLoginsExchangeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokers/tastytrade/authorize': typeof ApiBrokersTastytradeAuthorizeRoute
  '/api/brokers/tastytrade/callback': typeof ApiBrokersTastytradeCallbackRoute
  '/api/brokers/tastytrade/exchange': typeof ApiBrokersTastytradeExchangeRoute
  '/api/brokers/tastytrade/token': typeof ApiBrokersTastytradeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AppConnectRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/watch': typeof AppWatchRoute
  '/api/agent-logins': typeof ApiAgentLoginsRouteWithChildren
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-catalysts': typeof ApiPublicCatalystsRoute
  '/api/public-daily-briefs': typeof ApiPublicDailyBriefsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/connect/agent': typeof ConnectAgentRoute
  '/authorize': typeof AuthorizeIndexRoute
  '/api/agent-logins/exchange': typeof ApiAgentLoginsExchangeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokers/tastytrade/authorize': typeof ApiBrokersTastytradeAuthorizeRoute
  '/api/brokers/tastytrade/callback': typeof ApiBrokersTastytradeCallbackRoute
  '/api/brokers/tastytrade/exchange': typeof ApiBrokersTastytradeExchangeRoute
  '/api/brokers/tastytrade/token': typeof ApiBrokersTastytradeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/authorize': typeof AuthorizeRouteWithChildren
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/watch': typeof AppWatchRoute
  '/api/agent-logins': typeof ApiAgentLoginsRouteWithChildren
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-catalysts': typeof ApiPublicCatalystsRoute
  '/api/public-daily-briefs': typeof ApiPublicDailyBriefsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/connect/agent': typeof ConnectAgentRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/api/agent-logins/exchange': typeof ApiAgentLoginsExchangeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokers/tastytrade/authorize': typeof ApiBrokersTastytradeAuthorizeRoute
  '/api/brokers/tastytrade/callback': typeof ApiBrokersTastytradeCallbackRoute
  '/api/brokers/tastytrade/exchange': typeof ApiBrokersTastytradeExchangeRoute
  '/api/brokers/tastytrade/token': typeof ApiBrokersTastytradeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/disclosures'
    | '/privacy'
    | '/terms'
    | '/connect'
    | '/recommendations'
    | '/watch'
    | '/api/agent-logins'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-catalysts'
    | '/api/public-daily-briefs'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/connect/agent'
    | '/authorize/'
    | '/api/agent-logins/exchange'
    | '/api/auth/$'
    | '/api/brokers/tastytrade/authorize'
    | '/api/brokers/tastytrade/callback'
    | '/api/brokers/tastytrade/exchange'
    | '/api/brokers/tastytrade/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclosures'
    | '/privacy'
    | '/terms'
    | '/connect'
    | '/recommendations'
    | '/watch'
    | '/api/agent-logins'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-catalysts'
    | '/api/public-daily-briefs'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/connect/agent'
    | '/authorize'
    | '/api/agent-logins/exchange'
    | '/api/auth/$'
    | '/api/brokers/tastytrade/authorize'
    | '/api/brokers/tastytrade/callback'
    | '/api/brokers/tastytrade/exchange'
    | '/api/brokers/tastytrade/token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/authorize'
    | '/disclosures'
    | '/privacy'
    | '/terms'
    | '/_app/connect'
    | '/_app/recommendations'
    | '/_app/watch'
    | '/api/agent-logins'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-catalysts'
    | '/api/public-daily-briefs'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/connect/agent'
    | '/authorize/'
    | '/api/agent-logins/exchange'
    | '/api/auth/$'
    | '/api/brokers/tastytrade/authorize'
    | '/api/brokers/tastytrade/callback'
    | '/api/brokers/tastytrade/exchange'
    | '/api/brokers/tastytrade/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRouteWithChildren
  DisclosuresRoute: typeof DisclosuresRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAgentLoginsRoute: typeof ApiAgentLoginsRouteWithChildren
  ApiFavoritesRoute: typeof ApiFavoritesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpTokensRoute: typeof ApiMcpTokensRoute
  ApiPublicCatalystRefreshRoute: typeof ApiPublicCatalystRefreshRoute
  ApiPublicCatalystsRoute: typeof ApiPublicCatalystsRoute
  ApiPublicDailyBriefsRoute: typeof ApiPublicDailyBriefsRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  ApiPublicSymbolEvidenceRoute: typeof ApiPublicSymbolEvidenceRoute
  ApiPublicSymbolSearchRoute: typeof ApiPublicSymbolSearchRoute
  ApiPublicYearCandlesRoute: typeof ApiPublicYearCandlesRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiViewerRoute: typeof ApiViewerRoute
  ConnectAgentRoute: typeof ConnectAgentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBrokersTastytradeAuthorizeRoute: typeof ApiBrokersTastytradeAuthorizeRoute
  ApiBrokersTastytradeCallbackRoute: typeof ApiBrokersTastytradeCallbackRoute
  ApiBrokersTastytradeExchangeRoute: typeof ApiBrokersTastytradeExchangeRoute
  ApiBrokersTastytradeTokenRoute: typeof ApiBrokersTastytradeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agent-logins': {
      id: '/api/agent-logins'
      path: '/api/agent-logins'
      fullPath: '/api/agent-logins'
      preLoaderRoute: typeof ApiAgentLoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites': {
      id: '/api/favorites'
      path: '/api/favorites'
      fullPath: '/api/favorites'
      preLoaderRoute: typeof ApiFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-tokens': {
      id: '/api/mcp-tokens'
      path: '/api/mcp-tokens'
      fullPath: '/api/mcp-tokens'
      preLoaderRoute: typeof ApiMcpTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-catalyst-refresh': {
      id: '/api/public-catalyst-refresh'
      path: '/api/public-catalyst-refresh'
      fullPath: '/api/public-catalyst-refresh'
      preLoaderRoute: typeof ApiPublicCatalystRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-catalysts': {
      id: '/api/public-catalysts'
      path: '/api/public-catalysts'
      fullPath: '/api/public-catalysts'
      preLoaderRoute: typeof ApiPublicCatalystsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-daily-briefs': {
      id: '/api/public-daily-briefs'
      path: '/api/public-daily-briefs'
      fullPath: '/api/public-daily-briefs'
      preLoaderRoute: typeof ApiPublicDailyBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-snapshot': {
      id: '/api/public-snapshot'
      path: '/api/public-snapshot'
      fullPath: '/api/public-snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-symbol-evidence': {
      id: '/api/public-symbol-evidence'
      path: '/api/public-symbol-evidence'
      fullPath: '/api/public-symbol-evidence'
      preLoaderRoute: typeof ApiPublicSymbolEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-symbol-search': {
      id: '/api/public-symbol-search'
      path: '/api/public-symbol-search'
      fullPath: '/api/public-symbol-search'
      preLoaderRoute: typeof ApiPublicSymbolSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-year-candles': {
      id: '/api/public-year-candles'
      path: '/api/public-year-candles'
      fullPath: '/api/public-year-candles'
      preLoaderRoute: typeof ApiPublicYearCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/viewer': {
      id: '/api/viewer'
      path: '/api/viewer'
      fullPath: '/api/viewer'
      preLoaderRoute: typeof ApiViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizeIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/authorize/consent': {
      id: '/authorize/consent'
      path: '/consent'
      fullPath: '/authorize/consent'
      preLoaderRoute: typeof AuthorizeConsentRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/connect/agent': {
      id: '/connect/agent'
      path: '/connect/agent'
      fullPath: '/connect/agent'
      preLoaderRoute: typeof ConnectAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-logins/exchange': {
      id: '/api/agent-logins/exchange'
      path: '/exchange'
      fullPath: '/api/agent-logins/exchange'
      preLoaderRoute: typeof ApiAgentLoginsExchangeRouteImport
      parentRoute: typeof ApiAgentLoginsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/tastytrade/authorize': {
      id: '/api/brokers/tastytrade/authorize'
      path: '/api/brokers/tastytrade/authorize'
      fullPath: '/api/brokers/tastytrade/authorize'
      preLoaderRoute: typeof ApiBrokersTastytradeAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/tastytrade/callback': {
      id: '/api/brokers/tastytrade/callback'
      path: '/api/brokers/tastytrade/callback'
      fullPath: '/api/brokers/tastytrade/callback'
      preLoaderRoute: typeof ApiBrokersTastytradeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/tastytrade/exchange': {
      id: '/api/brokers/tastytrade/exchange'
      path: '/api/brokers/tastytrade/exchange'
      fullPath: '/api/brokers/tastytrade/exchange'
      preLoaderRoute: typeof ApiBrokersTastytradeExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/tastytrade/token': {
      id: '/api/brokers/tastytrade/token'
      path: '/api/brokers/tastytrade/token'
      fullPath: '/api/brokers/tastytrade/token'
      preLoaderRoute: typeof ApiBrokersTastytradeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppWatchRoute: typeof AppWatchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppWatchRoute: AppWatchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthorizeRouteChildren {
  AuthorizeConsentRoute: typeof AuthorizeConsentRoute
  AuthorizeIndexRoute: typeof AuthorizeIndexRoute
}

const AuthorizeRouteChildren: AuthorizeRouteChildren = {
  AuthorizeConsentRoute: AuthorizeConsentRoute,
  AuthorizeIndexRoute: AuthorizeIndexRoute,
}

const AuthorizeRouteWithChildren = AuthorizeRoute._addFileChildren(
  AuthorizeRouteChildren,
)

interface ApiAgentLoginsRouteChildren {
  ApiAgentLoginsExchangeRoute: typeof ApiAgentLoginsExchangeRoute
}

const ApiAgentLoginsRouteChildren: ApiAgentLoginsRouteChildren = {
  ApiAgentLoginsExchangeRoute: ApiAgentLoginsExchangeRoute,
}

const ApiAgentLoginsRouteWithChildren = ApiAgentLoginsRoute._addFileChildren(
  ApiAgentLoginsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthorizeRoute: AuthorizeRouteWithChildren,
  DisclosuresRoute: DisclosuresRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAgentLoginsRoute: ApiAgentLoginsRouteWithChildren,
  ApiFavoritesRoute: ApiFavoritesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpTokensRoute: ApiMcpTokensRoute,
  ApiPublicCatalystRefreshRoute: ApiPublicCatalystRefreshRoute,
  ApiPublicCatalystsRoute: ApiPublicCatalystsRoute,
  ApiPublicDailyBriefsRoute: ApiPublicDailyBriefsRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  ApiPublicSymbolEvidenceRoute: ApiPublicSymbolEvidenceRoute,
  ApiPublicSymbolSearchRoute: ApiPublicSymbolSearchRoute,
  ApiPublicYearCandlesRoute: ApiPublicYearCandlesRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiViewerRoute: ApiViewerRoute,
  ConnectAgentRoute: ConnectAgentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBrokersTastytradeAuthorizeRoute: ApiBrokersTastytradeAuthorizeRoute,
  ApiBrokersTastytradeCallbackRoute: ApiBrokersTastytradeCallbackRoute,
  ApiBrokersTastytradeExchangeRoute: ApiBrokersTastytradeExchangeRoute,
  ApiBrokersTastytradeTokenRoute: ApiBrokersTastytradeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
